# Generated by Django 6.0.6 on 2026-07-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomba_subaccount_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nomba_subaccount_ref', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='business',
        ),
        migrations.RemoveField(
            model_name='event',
            name='business',
        ),
        migrations.AddField(
            model_name='apikey',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.organizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.organizer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
